version: '3.8'
services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
   # environment:
    #  MONGO_INITDB_ROOT_USERNAME: aakash
    #  MONGO_INITDB_ROOT_PASSWORD: Adminer121
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
