global:
  scrape_interval: 2s
  evaluation_interval: 2s


# Define scrape configurations.
scrape_configs:
  # Scrape Prometheus's own metrics.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9003' ] # only for demo purposes

  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9000'] # only for demo purposes
        labels:
          application: 'Product Service'

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9002' ] # only for demo purposes
        labels:
          application: 'Order Service'

  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9001' ] # only for demo purposes
        labels:
          application: 'Inventory Service'

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9003' ] # only for demo purposes
        labels:
          application: 'Notification Service'